os:
  - linux
dist: bionic
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coverage
  - sudo apt install ruby-coveralls
language: python

stages:
- name: test

jobs:
  include:
    - &test
      stage: test
      name: Run linting and unit tests
      python: 3.6
      script:
        - flake8
        - coverage run --source pubgrade -m pytest
        - coveralls
    - <<: *test
      python: 3.7
    - <<: *test
      python: 3.8
    - <<: *test
      python: 3.9