version: '3.6'
services:
    broker:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
        command: bash -c "cd /app/broker; python app.py"
        volumes:
            - /home/akash/Desktop/ELIXIR/containerMount/broker/:/app
        ports:
            - "8080:8080"

    mongodb: 
        image: mongo:3.6
        restart: unless-stopped
        volumes:
            - ../data/broker/db:/data/db
        ports:
            - "27017:27017"
