apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - args:
    - --dockerfile=/file/sGwDmb.ls~_i/drs-filer./Dockerfile
    - --destination=akash7778/test-image:v0.0.1
    - --context=/file/sGwDmb.ls~_i/drs-filer
    image: gcr.io/kaniko-project/executor:v0.22.0
    name: kaniko
    env:
      - name: BUILDNAME
        value: 'BUILDNAME'
      - name: ACCESSTOKEN
        value: 'ACCESS_TOKEN'
      - name: NAMESPACE
        value: 'NAMESPACE'
      - name: BROKER_URL
        value: 'BROKER_URL'
      - name: BROKER_PORT
        value: 'BROKER_PORT'
    volumeMounts:
    - mountPath: /broker_temp_files
      name: pv-storage
    - mountPath: /kaniko/.docker/config.json
      name: pv-storage
      subPath: config.json
  restartPolicy: Never
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim
