apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - args:
    - --dockerfile=/file/sGwDmb.ls~_i/drs-filer./Dockerfile
    - --destination=akash7778/test-image:v0.0.1
    - --context=/file/sGwDmb.ls~_i/drs-filer
    image: gcr.io/kaniko-project/executor:v0.22.0
    name: kaniko
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "curl --location --request GET 'http://192.168.99.100:30352/repositories'"] # create a callback to update timestamp,remove temp files and trigger subscriptions
    volumeMounts:
    - mountPath: /broker_temp_files
      name: pv-storage
    - mountPath: /kaniko/.docker/config.json
      name: pv-storage
      subPath: config.json
  restartPolicy: Never
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim