apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-complete-updater
spec:
 replicas: {{ .Values.pubgrade_build_complete_updater.replicaCount }}
 selector:
   matchLabels:
     app: {{ .Values.appName }}
 template:
   metadata:
     labels:
       app: {{ .Values.appName }}
   spec:
          serviceAccountName: {{ .Values.pubgrade_webserver.serviceAccountName }}
          automountServiceAccountToken: true
          containers:
          - image: {{ .Values.pubgrade_build_complete_updater.image }}
            name: pubgrade-build-complete-updater
            imagePullPolicy: {{ .Values.pubgrade_build_complete_updater.imagePullPolicy }}
            env:
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
              - name: BROKER_URL
                value: {{ .Values.pubgrade_url }}
