apiVersion: apps/v1
kind: Deployment
metadata:
 name: broker
spec:
 replicas: 1
 selector:
   matchLabels:
     app: broker
 template:
   metadata:
     labels:
       app: broker
   spec:
     serviceAccountName: broker
     automountServiceAccountToken: true
     containers:
     - name: broker
       imagePullPolicy: IfNotPresent
       image: akash7778/broker:v1.0.0
       ports:
       - containerPort: 8080
       volumeMounts:
       - mountPath: /broker_temp_files  # if changed needs to be changed at builds.py
         name: pv-storage
       env:
         - name: NAMESPACE
           value: {{ .Release.Namespace }}
         - name: PV_NAME
           value: {{ .Values.pvClaimName }}
     volumes:
       - name: pv-storage
         persistentVolumeClaim:
               claimName: {{ .Values.pvClaimName }}
