apiVersion: apps/v1
kind: Deployment
metadata:
 name: pubgrade
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pubgrade
 template:
   metadata:
     labels:
       app: pubgrade
   spec:
     serviceAccountName: pubgrade
     automountServiceAccountToken: true
     containers:
     - name: pubgrade
       imagePullPolicy: IfNotPresent
       image: akash7778/pubgrade:test_build
       ports:
       - containerPort: 8080
       volumeMounts:
       - mountPath: /pubgrade_temp_files  # if changed needs to be changed at builds.py
         name: pv-storage
       env:
         - name: NAMESPACE
           value: {{ .Release.Namespace }}
         - name: PV_NAME
           value: {{ .Values.pvClaimName }}
     volumes:
       - name: pv-storage
         persistentVolumeClaim:
               claimName: {{ .Values.pvClaimName }}
