apiVersion: apps/v1
kind: Deployment
metadata:
 name: pubgrade
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pubgrade
 template:
   metadata:
     labels:
       app: pubgrade
   spec:
     serviceAccountName: pubgrade
     automountServiceAccountToken: true
     securityContext:
        runAsUser: 1000
     containers:
     - name: pubgrade
       imagePullPolicy: Always
       image: akash7778/pubgrade:test_build_1
       ports:
       - containerPort: 8080
       volumeMounts:
       - mountPath: {{ .Values.volumes.Pubgrade.pathToMountedDir }}
         name: pubgrade-storage
       env:
         - name: NAMESPACE
           value: {{ .Release.Namespace }}
         - name: PV_NAME
           value: {{ .Values.volumes.Pubgrade.name }}
         - name: BASE_DIR
           value: {{ .Values.volumes.Pubgrade.pathToMountedDir }}
     volumes:
       - name: pubgrade-storage
         persistentVolumeClaim:
               claimName: {{ .Values.volumes.Pubgrade.name }}
     initContainers:
        - name: take-data-dir-ownership
          image: alpine:3
          command:
          - ls
          volumeMounts:
          - name: pubgrade-storage
            mountPath: {{ .Values.volumes.Pubgrade.pathToMountedDir }}
