apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-complete-updater
spec:
 replicas: 1
 selector:
   matchLabels:
     app: broker
 template:
   metadata:
     labels:
       app: broker
   spec:
          serviceAccountName: broker
          automountServiceAccountToken: true
          containers:
          - image: {{ .Values.imageNotifyCompletion }}
            name: notify-completion
            imagePullPolicy: IfNotPresent
