apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-complete-updater
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pubgrade
 template:
   metadata:
     labels:
       app: pubgrade
   spec:
          serviceAccountName: pubgrade
          automountServiceAccountToken: true
          containers:
          - image: {{ .Values.imageNotifyCompletion }}
            name: notify-completion
            imagePullPolicy: IfNotPresent
            env:
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
              - name: BROKER_URL
                value: {{ .Values.pubgrade_URL }}
