# apiVersion: v1
# kind: PersistentVolume
# metadata:
#  name: {{ .Values.pvClaimName }}
#  labels:
#    type: local
# spec:
#  storageClassName: manual
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: {{ .Values.pathToLocalDir }}
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ .Values.pvClaimName }}
spec:
 storageClassName: "glusterfs-storage"
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
