{{ if .Values.volumes.Pubgrade.deployLocalPv }}
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pubgrade-pv
 labels:
   type: local
spec:
 storageClassName: {{ .Values.volumes.Pubgrade.storageClass }}
 capacity:
   storage: 2Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: {{ .Values.pathToLocalDir }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ .Values.volumes.Pubgrade.name }}
spec:
 storageClassName: {{ .Values.volumes.Pubgrade.storageClass }}
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: {{ .Values.volumes.Pubgrade.size }}
