apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-pods
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: pubgrade
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: role-pubgrade
  apiGroup: rbac.authorization.k8s.io
