apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pubgrade_mongodb.name }}
  labels:
    app: db
spec:
  replicas: {{ .Values.pubgrade_mongodb.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      securityContext:
        runAsUser: {{ .Values.pubgrade_mongodb.securityContext.runAsUser }}
      containers:
      - name: mongodb
        image: {{ .Values.pubgrade_mongodb.image }}
        ports:
        - containerPort: {{ .Values.pubgrade_mongodb.port }}
          name: db-container
        volumeMounts:
          - mountPath: /data/db
            name: {{ .Values.pubgrade_mongodb.volume.name }}
      volumes:
       - name: {{ .Values.pubgrade_mongodb.volume.name }}
         persistentVolumeClaim:
               claimName: {{ .Values.pubgrade_mongodb.volume.claimName }}
 