{{ if .Values.pubgrade_mongodb.volume.storageActive }}
{{ if .Values.pubgrade_mongodb.volume.deployLocalPv }}
apiVersion: v1
kind: PersistentVolume
metadata:
 name: mongo-pv
 labels:
   type: local
spec:
 storageClassName: {{ .Values.pubgrade_mongodb.volume.storageClass }}
 capacity:
   storage: {{ .Values.pubgrade_mongodb.volume.size }}
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: {{ .Values.pubgrade_mongodb.volume.pathToLocalDir }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ .Values.pubgrade_mongodb.volume.claimName }}
spec:
 storageClassName: {{ .Values.pubgrade_mongodb.volume.storageClass }}
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: {{ .Values.pubgrade_mongodb.volume.size }}
{{ end }}
