apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pubgrade_mongodb.name }}
  labels:
    app: db
spec:
  ports:
  - port: {{ .Values.pubgrade_mongodb.port }}
    protocol: TCP
    name: {{ .Values.pubgrade_mongodb.name }}
  selector:
    app: db
  type: {{ .Values.pubgrade_mongodb.portType }}