apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.pubgrade_webserver.serviceAccountName }}
      automountServiceAccountToken: true
      containers:
        - name: pubgrade
          imagePullPolicy: {{ .Values.pubgrade_webserver.imagePullPolicy }}
          image: {{ .Values.pubgrade_webserver.image }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            runAsUser: 1000
          ports:
            - containerPort: {{ .Values.pubgrade_webserver.port }}
          volumeMounts:
            - mountPath: {{ .Values.pubgrade_webserver.volume.pathToMountedDir }}
              name: pubgrade-storage
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PV_NAME
              value: {{ .Values.pubgrade_webserver.volume.pvcName }}
            - name: BASE_DIR
              value: {{ .Values.pubgrade_webserver.volume.pathToMountedDir }}
            - name: PUBGRADE_URL
              value: {{ .Values.pubgrade_url }}
            - name: GH_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pubgrade-secret
                  key: gh_access_token
            - name: COSIGN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pubgrade-secret
                  key: cosign_password
            - name: COSIGN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: pubgrade-secret
                  key: cosign_private_key
            - name: INTERMEDIATE_REGISTRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pubgrade-secret
                  key: intermediate_registry_token
      volumes:
        - name: pubgrade-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pubgrade_webserver.volume.pvcName }}
