{{- if  .Values.pubgrade_webserver.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.pubgrade_webserver.ingress.https.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.pubgrade_webserver.ingress.https.issuer }}
    kubernetes.io/tls-acme: {{ quote .Values.pubgrade_webserver.ingress.https.enabled}}
    {{- end }}
  name: pubgrade-ingress
spec:
  rules:
  - host: {{ .Values.pubgrade_webserver.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: pubgrade-service
            port:
              number:  {{ .Values.pubgrade_webserver.port }}
        path: /
        pathType: Prefix
  {{- if .Values.pubgrade_webserver.ingress.https.enabled }}
  tls:
  - hosts:
    - {{ .Values.pubgrade_webserver.ingress.url }}
    secretName: pubgrade-ingress-secret
  {{- end }}
{{- else if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pubgrade-ingress
spec:
  host: {{ .Values.pubgrade_webserver.ingress.url }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pubgrade-service
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
{{- end }}