{{ if .Values.pubgrade_webserver.volume.storage_active }}
{{ if .Values.pubgrade_webserver.volume.deployLocalPv }}
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pubgrade-pv
 labels:
   type: local
spec:
 storageClassName: {{ .Values.pubgrade_webserver.volume.storageClass }}
 capacity:
   storage: {{ .Values.pubgrade_webserver.volume.size }}
 accessModes:
   - ReadWriteMany
 hostPath:
   path: {{ .Values.pubgrade_webserver.volume.pathToLocalDir }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ .Values.pubgrade_webserver.volume.pvcName }}
spec:
 storageClassName: {{ .Values.pubgrade_webserver.volume.storageClass }}
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: {{ .Values.pubgrade_webserver.volume.size }}
{{ end }}