apiVersion: v1
kind: Service
metadata:
  name: pubgrade-service
spec:
  type: {{ .Values.pubgrade_webserver.portType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.pubgrade_webserver.port }}
      targetPort: {{ .Values.pubgrade_webserver.port }}
      nodePort: 30008
