name: Build and Publish Docker Image

on:
  push:
    branches:
      - github_actions  # will be changed to dev, once tested

jobs:
  build-and-publish:
    name: Build and publish app image
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate tag
        run: |
          echo "TAG=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Build and publish Pubgrade image
        id: pubgrade-image
        uses: philips-software/docker-ci-scripts@v5.0.0
        with:
          dockerfile: .
          image-name: "pubgrade"
          tags: "latest ${{ env.TAG }}"
          push-branches: "github_actions {{ github.event.repository.default_branch }}$"
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_LOGIN }}
          REGISTRY_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
          DOCKER_ORGANIZATION: ${{ secrets.DOCKERHUB_ORG }}
          GITHUB_ORGANIZATION: ${{ github.repository_owner }}
      - name: Build and publish Pubgrade-Updater image
        id: pubgrade-updater-image
        uses: philips-software/docker-ci-scripts@v5.0.0
        with:
          dockerfile: build-complete-updater/Dockerfile
          image-name: "pubgrade-updater"
          tags: "latest ${{ env.TAG }}"
          push-branches: "github_actions {{ github.event.repository.default_branch }}$"
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_LOGIN }}
          REGISTRY_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
          DOCKER_ORGANIZATION: ${{ secrets.DOCKERHUB_ORG }}
          GITHUB_ORGANIZATION: ${{ github.repository_owner }}
      - name: Verify that image was pushed
        run: |
          echo "Push indicator: ${{ steps.docker.outputs.push-indicator }}"
          echo "# Set to 'true' if image was pushed, empty string otherwise"
          test "${{ steps.pubgrade-image.outputs.push-indicator }}" == "true"
          test "${{ steps.pubgrade-updater-image.outputs.push-indicator }}" == "true"
